openapi: 3.0.2
info:
  title: My API
  version: 1.0.0

paths:
  /books:
    get:
      operationId: main.get_books_route
      tags:
        - Books
      responses:
        '200':
          description: List of all books
        '400':
          description: Database error
    post:
      operationId: main.add_book_route
      tags:
        - Books
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  _id:
                    type: string
        '400':
          description: Bad request (invalid book data or database error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /books/isbn/{isbn}:
    get:
      operationId: main.get_book_route
      tags:
        - Books
      parameters:
        - in: path
          name: isbn
          schema:
            type: integer
          required: true
          description: ISBN of the book
      responses:
        '200':
          description: Book data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Book not found
    put:
      operationId: main.update_book_route
      tags:
        - Books
      parameters:
        - in: path
          name: isbn
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Updated book data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Bad request
        '404':
          description: Book not found
    delete:
      operationId: main.delete_book_route
      tags:
        - Books
      parameters:
        - in: path
          name: isbn
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Book deleted successfully
        '400':
          description: Bad request
        '404':
          description: Book not found
  /books/search:
    get:
      operationId: main.search_books_route
      tags:
        - Books
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: false
          description: Query for searching books
      responses:
        '200':
          description: List of matching books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Database error
  /books/author/{author_name}:
    get:
      operationId: main.get_books_by_author_route
      tags:
        - Books
      parameters:
        - in: path
          name: author_name
          schema:
            type: string
          required: true
          description: Author's name
      responses:
        '200':
          description: List of books by the specified author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Database error
  /books/random:
    get:
      operationId: main.get_random_book_route
      tags:
        - Books
      responses:
        '200':
          description: A random book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Database error
        '404':
          description: No books available

components:
  schemas:
    Book:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
        ean_isbn13:
          type: integer
          description: EAN ISBN13 code of the book
        title:
          type: string
          description: Title of the book
        creators:
          type: string
          description: Comma-separated list of book creators
        firstName:
          type: string
          description: First name of the primary creator
        lastName:
          type: string
          description: Last name of the primary creator
        description:
          type: string
          description: Description of the book
        publisher:
          type: string
          description: Publisher of the book
        publishDate:
          type: string
          format: date
          description: Publish date of the book (in the format "YYYY-MM-DD")
        price:
          type: number
          format: float
          description: Price of the book
        length:
          type: integer
          format: int32
          description: Length or number of pages in the book
